version: "3.8"

services:
  db:
    container_name: db
    image: mongo
    restart: always
    command: --auth
    ports:
      - 27017:27017
    env_file:
      - ./db/config.env
    volumes:
      - ./db/db:/data/db
      - ./db/init_db:/docker-entrypoint-initdb.d
